### PR TITLE
Fix Toon reboot

### PR DESCRIPTION
**Pull request by ualex73**

### CODE REVIEW

**Comment by RudolfRendier** [comment]
Nice fix! I worked around this by clearing the cache with a cron-job as stated here:
https://www.domoticaforum.eu/viewtopic.php?f=104&t=11968

I shared a link to this fix in that topic; thanks for sharing!

**Comment by ualex73** [comment]
The Eneco Toon still reboots every 7+ days, not sure why ... Also the GUI reboots regularly, but that's less service affection ;-) But with this fix, much better then before.

**Comment by RudolfRendier** [comment]
Toon can do better than that, my toon is running for 30 days and I think I initiated that last reboot myself.

```
eneco-xxx-xxxxxxxx:~# uptime
 11:44:05 up 30 days, 15:28,  0 users,  load average: 0.28, 0.43, 0.36

I suggest you check other custom apps; I doubt this custom_component is still an issue.
Good luck.

**Comment by ualex73** [comment]
Yes, i need to monitor a bit better. It was going a long time, before i enabled the OpenTherm option ;-) I only have enabled the thermostat and the boilerstatus.

**Comment by cyberjunky** [comment]
Thanks, I had never issue with my Toon rebooting, but I merge it anyway.

**Comment by ualex73** [comment]
I think i 'fixed' the rebooting of Toon, i removed all addons except the boiler and afvalwijzer ... Now it is stable for 12+ days.

**Pull request merged**
