### PR TITLE
Changed: Fixing the ever changing devid's by Toon P1 meter

### PR DESCRIPTION
**Pull request by ualex73**

### CODE REVIEW

**Comment by cyberjunky** [comment]
Alex, it doesn't seem to work for me, self._state stays empty...

**Comment by ualex73** [comment]
:-(

How does your P1 meter output look like? Maybe we can spot it there ...

**Comment by cyberjunky** [comment]
```
{'dev_settings_device': {'uuid': 'f7dc198c-b2c3-47e1-8ee6-df10c0c85429', 'name': 'settings_device', 'internalAddress': 'settings_device', 'type': 'settings_device'}, 'dev_3': {'uuid': 'bcc006b0-4885-4e47-a862-c7d4bc295e61', 'name': 'HAE_METER_v2', 'internalAddress': '3', 'type': 'HAE_METER_v2', 'supportsCrc': '1', 'ccList': '22 3c 3d 3e 56 60 70 72 7a 86 8b 73', 'supportedCC': '22 3c 3d 3e 56 60 70 72 7a 86 8b 73', 'nodeFlags': [], 'IsConnected': '1', 'HealthValue': '10', 'DeviceName': 'HAE_METER_v2'}, 'dev_3.1': {'uuid': '4acee8d7-d74e-490a-9b90-c9fb11c7b1e5', 'name': 'HAE_METER_v2_1', 'internalAddress': '3.1', 'type': 'HAE_METER_v2_1', 'supportsCrc': '0', 'ccList': '3c 3d 3e 72 86', 'supportedCC': '3c 3d 3e 72 86', 'nodeFlags': [], 'CurrentGasFlow': '98.00', 'CurrentGasQuantity': '5462607.00', 'DeviceName': 'HAE_METER_v2_1'}, 'dev_3.2': {'uuid': '7842483d-4fb3-4c6a-b26f-163f85429e08', 'name': 'HAE_METER_v2_2', 'internalAddress': '3.2', 'type': 'HAE_METER_v2_2', 'supportsCrc': '0', 'ccList': '3c 3d 3e 72 86', 'supportedCC': '3c 3d 3e 72 86', 'nodeFlags': [], 'DeviceName': 'HAE_METER_v2_2', 'CurrentElectricityFlow': 'NaN', 'CurrentElectricityQuantity': 'NaN'}, 'dev_3.3': {'uuid': '7efb372d-d287-4556-b03e-c8e92c1ed261', 'name': 'HAE_METER_v2_3', 'internalAddress': '3.3', 'type': 'HAE_METER_v2_3', 'supportsCrc': '0', 'ccList': '3c 3d 3e 72 86', 'supportedCC': '3c 3d 3e 72 86', 'nodeFlags': [], 'DeviceName': 'HAE_METER_v2_3', 'CurrentElectricityFlow': '0.00', 'CurrentElectricityQuantity': '13149037.00'}, 'dev_3.4': {'uuid': '430ffe71-118c-4975-b1df-b20f49dad085', 'name': 'HAE_METER_v2_4', 'internalAddress': '3.4', 'type': 'HAE_METER_v2_4', 'supportsCrc': '0', 'ccList': '3c 3d 3e 72 86', 'supportedCC': '3c 3d 3e 72 86', 'nodeFlags': [], 'DeviceName': 'HAE_METER_v2_4', 'CurrentElectricityFlow': '0.00', 'CurrentElectricityQuantity': '2311966.00'}, 'dev_3.5': {'uuid': 'f71bb8c8-5457-482c-b28e-36246556e4ca', 'name': 'HAE_METER_v2_5', 'internalAddress': '3.5', 'type': 'HAE_METER_v2_5', 'supportsCrc': '0', 'ccList': '3c 3d 3e 72 86', 'supportedCC': '3c 3d 3e 72 86', 'nodeFlags': [], 'DeviceName': 'HAE_METER_v2_5', 'CurrentElectricityFlow': '0.00', 'CurrentElectricityQuantity': '12604066.00'}, 'dev_3.6': {'uuid': '6271fe58-cf4c-46ab-9c5d-5cb957008d85', 'name': 'HAE_METER_v2_6', 'internalAddress': '3.6', 'type': 'HAE_METER_v2_6', 'supportsCrc': '0', 'ccList': '3c 3d 3e 72 86', 'supportedCC': '3c 3d 3e 72 86', 'nodeFlags': [], 'DeviceName': 'HAE_METER_v2_6', 'CurrentElectricityFlow': '240.00', 'CurrentElectricityQuantity': '846780.00'}}

**Comment by ualex73** [comment]
Ok, in your json output there is no "type" field ... But comparing it to my
output, we should be able to use "deviceName" ... That one seems
consistent. I will make a new pull request with this information ;-)

Op zo 20 jan. 2019 om 13:26 schreef Ron Klinkien <notifications@github.com>:

**Comment by ualex73** [comment]
Done 👍

**Comment by cyberjunky** [comment]
Yes this one works for me too!

**Comment by ualex73** [comment]
:+1: Only the solar one should be 'fixed' too, but i don't have an example of the such json device.

**Pull request merged**
